### ISSUE TITLE
Runtime error after trying to flatten

### ISSUE THREAD

**Issue by MichelleEmmert** [datascience-mobi/2021-topic-04-team-05#2]
https://github.com/datascience-mobi/2021-topic-04-team-05/blob/6ad5474945c345ea23b6ebd9b2bdf2a6c46e3bc7/SVM_Segmentation/PCA.py#L33

@npeschke 

After flattening and reshaping the arrays, we have one sample and more 1024*1024 features, but the PCA-function only accepts values between 0 and min(n_samples, n_features)=1. I did not find a solution for that or another function and am a bit confused now, how I can avoid that it wants a value between 0 and 1 and not between 0 and n_features. Also after changing it to 1, just to try it out, it gives me a runtime error I do not understand.

**Comment by npeschke** [comment]
I have no error running the PCA.py file on my end. Please provide more info about how I can reproduce the issue.
