### ISSUE TITLE
Error: images of different shapes can't be broadcasted together

### ISSUE THREAD

**Issue by MichelleEmmert** [datascience-mobi/2021-topic-04-team-05#3]
So, I am trying to overwrite random pixels of a background with the values of the new object/cell, but for some reason I always get 2 different shapes in the end, which of course can't be broadcasted together and I cannot find the reason for that.

https://github.com/datascience-mobi/2021-topic-04-team-05/blob/6577987cc4bb01584d980f47ec00246b278ff309/SVM_Segmentation/Synthetic_images/cell_images.py#L202

@npeschke

**Comment by npeschke** [comment]
You already force the slice to be 0 the line before, so you can just add object1 to the slice

**Comment by MichelleEmmert** [comment]
So I updated/fused these lines, but this is not the issue here. I still get the same error:

background2[y:y + h, x:x + w] = 0 + object1
ValueError: could not broadcast input array from shape (100,100) into shape (76,100)

And I do not really understand why, because I checked the shapes before, and they actually are the same, but when I am trying to substitute the values, it always gives me this error.
@npeschke

**Comment by npeschke** [comment]
how about

`background2[y:y + h, x:x + w] += object1`

**Comment by MichelleEmmert** [comment]
So, I tried to change the borders, the image can be pasted in...but it still does not work. With a definite number in the borders, like 500 it does, but if I just substract the shape of the object/cell image I want to paste in, it does not. 

But the overwriting works perfectly :) We get a wonderful cell in the middle of the image (of course just one, because we set a definite number)

@npeschke

**Comment by npeschke** [comment]
Could you give me a direct reference to the stuff that does not work? Otherwise I am not able to reproduce the problem that you are describing.

**Comment by MichelleEmmert** [comment]
So in the same python file, in **line 203 and 207** I am trying to select the maximum coordinates where the object can be pasted in. This was what we talked about in the Tutorium, that this probably is the issue. 
But if I run it I get the exact same error as referenced before, so that the shapes cannot be broadcasted together.

If I set x and y to a definite number like 500, it works.

@npeschke

**Comment by npeschke** [comment]
If I run [this script](https://github.com/datascience-mobi/2021-topic-04-team-05/blob/9969e27f/SVM_Segmentation/Synthetic_images/cell_images.py)  I get the following error:

```
Traceback (most recent call last):
  File "/home/npeschke/gitRepos/teaching/data_analysis/2021/group_projects/group_5/SVM_Segmentation/Synthetic_images/cell_images.py", line 150, in <module>
    selection(image, 'base_dir', 1, [0, 0, 200, 200], [750, 760, 100, 100], [200, 500, 50, 50])
TypeError: selection() takes 5 positional arguments but 6 were given
```

Besides that, `max_x` and `max_y` don't seem to be used anywhere else.
https://github.com/datascience-mobi/2021-topic-04-team-05/blob/9969e27ff93fc36d0951cf548a2cb27eed06ea86/SVM_Segmentation/Synthetic_images/cell_images.py#L202-L212

**Comment by MichelleEmmert** [comment]
I solved problems, code works now perfectly :)

@npeschke
