### ISSUE TITLE
SVM calculates the same loss for every column, the loss does not increase and it takes hours to calculate anything.

### ISSUE THREAD

**Issue by MichelleEmmert** [datascience-mobi/2021-topic-04-team-05#4]
https://github.com/datascience-mobi/2021-topic-04-team-05/blob/4513ac6d58a8bd00bfb5cbb63ab551c709fef01e/SVM_Segmentation/svm.py#L222

So beginning from line 222 we tested our svm, with an reduced input of about 3000 pixels, 2 images. The issue is, that the svm does not really 'learn'. This gets clear if you run the script after a while you do not get an increasing loss, which is a huge indicator that something is wrong. Additionally the weight calculated for each column, is the same, which also should not be the case.
Lastly the svm takes hours to calculate even our reduced image of about 3000 pixels, an by now we could not get any segmented image.

@npeschke

**Comment by npeschke** [comment]
https://github.com/datascience-mobi/2021-topic-04-team-05/blob/4513ac6d58a8bd00bfb5cbb63ab551c709fef01e/SVM_Segmentation/svm.py#L101
Script does not run because of error in `stochastic_gradient_descent` -> non-default parameter follows default parameter

https://github.com/datascience-mobi/2021-topic-04-team-05/blob/4513ac6d58a8bd00bfb5cbb63ab551c709fef01e/SVM_Segmentation/svm.py#L184-L187
This loop is likely not doing what you intend it to do.

The entire script runs -after fixing the issue in `stochastic_gradient_descent`- in under a second in my machine but does also not produce any output, `main` returns two empty lists.

**Comment by MichelleEmmert** [comment]
so I corrected all errors that came up. The reason why the output were two empty lists, was also because one of those mistakes, but now I fixed that an it runs and the exact issue that I described before appears.

The loop you mentioned is supposed to split the data (so split the different images into as many groups as we set) and if I run the debugger and look at the variables this for loop does exactly that, therefore I am not sure why you think this for loop is not doing what we want :/. 

About the issue: I now ran the corrected script for 1 hour and it is now at epoch 64 (of max 5000), and the loss still does not increase significantly. Now you should see it too if you run it.

@npeschke

**Comment by npeschke** [comment]
I let it run on my side for a bit with the following result:
```bash
1. epoch: current loss is 237502061.77872184.
2. epoch: current loss is 221911448.5255865.
4. epoch: current loss is 240370479.65315646.
8. epoch: current loss is 212444867.56486127.
16. epoch: current loss is 236095839.42584744.
32. epoch: current loss is 231873538.0147034.
64. epoch: current loss is 231810995.59532636.
The weights vector is: [-9659.8216879 -9659.8216879]
Traceback (most recent call last):
  File "/home/npeschke/gitRepos/teaching/data_analysis/2021/group_projects/group_5/SVM_Segmentation/svm.py", line 242, in <module>
    print(main(img_df, gt_df, 0))
  File "/home/npeschke/gitRepos/teaching/data_analysis/2021/group_projects/group_5/SVM_Segmentation/svm.py", line 216, in main
    y_pred = np.sign(np.dot(img_train.to_numpy()[i], W))
AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

Process finished with exit code 1
```
Regarding the loop:
you iteratively assign to the same names aka `split_data`, `gt_train` etc. apart from the fact that `gt_test` is never used anywhere else in the script, the loop just runs through and you continue with the latest data without doing anything with the data of the previous iteration.
This is the case for all loops in the following chunk:
https://github.com/datascience-mobi/2021-topic-04-team-05/blob/8884ae04ec3cd6634749a90298f53496d881af69/SVM_Segmentation/svm.py#L185-L206

**Comment by npeschke** [comment]
Have you tried running with smaller test data yet to decrease run times while debugging?

**Comment by lasanpla** [comment]
@npeschke in my branch (Laura) there is inside SVM_Segmentation a svm_test.py, which is is the same principle as your code in the master branch, but only applied to one image so that the run time is shorter, and instead of doing cross validation and diving it on the columns (=images), it divides the rows (=pixels), and has a canny and Otsu filter as added features. It always gives a weight vector which consists of the same numbers and doesn't classify the pixels... They're always 1, no matter the image or its quality (=size of the tiles)

**Comment by npeschke** [comment]
@lasanpla [this module](https://github.com/datascience-mobi/2021-topic-04-team-05/blob/50272527a4498e6dde6b7e5076627b107ed85085/SVM_Segmentation/svm_test.py) seems to be a completely different svm implementation. 

It might be a good idea to define a proper dummy dataset to debug the svm implementation. Like a hand curated array of easily interpretable values. And then feed that to the svm directly without any preprocessing.

**Comment by MichelleEmmert** [comment]
@npeschke So I now tried correcting all errors with a small test dataset. 
I now have an error, which is because of the length of the list img_train_new  (line 255), which is supposed to be as long as W, but isn't and I cannot figure out why. Both are created in the function stochastic_gradient_descent (as array_of_weigths_list and x_with_intercept_list). 

The other issue is, that all the calculated weights are always negative, that is the reason why all our pixels or values get assigned -1 and therefore there is no proper assignement/labeling happening. But I can't see how we can change/improve that.

**Comment by npeschke** [comment]
Please get rid of the preprocessing in the `svm` module ... the `main` function is so cluttered with stuff that has nothing to do with the SVM and more specifically its debugging that it is really hard to understand what is going on.
Then have a look at the data that is fed to the `stochastic_gradient_descent` function - especially the labels.
